module.exports = {
  getSubredditList,
};

// --- Type and status are not checked ---
const subredditArr = [
  { id: 1, name: "memes", type: "sfw", status: "active" },
  { id: 2, name: "dankmemes", type: "sfw", status: "active" },
  { id: 3, name: "wholesomememes", type: "sfw", status: "active" },
  { id: 4, name: "funny", type: "sfw", status: "active" },
  { id: 5, name: "me_irl", type: "sfw", status: "unknown" },
  { id: 6, name: "2meirl4meirl", type: "sfw", status: "unknown" },
  { id: 7, name: "OkBuddyRetard", type: "sfw", status: "unknown" },
  { id: 8, name: "reactiongifs", type: "sfw", status: "unknown" },
  { id: 9, name: "perfectlytimedpics", type: "sfw", status: "unknown" },
  { id: 10, name: "hmmm", type: "sfw", status: "unknown" },
  { id: 11, name: "instant_regret", type: "sfw", status: "unknown" },
  { id: 12, name: "therewasanattempt", type: "sfw", status: "active" },
  { id: 13, name: "ExpectationVsReality", type: "sfw", status: "unknown" },
  { id: 14, name: "AnimalsBeingDerps", type: "sfw", status: "unknown" },
  { id: 15, name: "PhotoshopBattles", type: "sfw", status: "unknown" },
  { id: 16, name: "HistoryMemes", type: "sfw", status: "active" },
  { id: 17, name: "PrequelMemes", type: "sfw", status: "unknown" },
  { id: 18, name: "SequelMemes", type: "sfw", status: "unknown" },
  { id: 19, name: "Animemes", type: "sfw", status: "active" },
  { id: 20, name: "GamingMemes", type: "sfw", status: "unknown" },
  { id: 21, name: "TechHumor", type: "sfw", status: "unknown" },
  { id: 22, name: "BoneAppleTea", type: "sfw", status: "unknown" },
  { id: 23, name: "Engrish", type: "sfw", status: "unknown" },
  { id: 24, name: "ComedyCemetery", type: "sfw", status: "unknown" },
  { id: 25, name: "Tumblr", type: "sfw", status: "unknown" },
  { id: 26, name: "ATBGE", type: "sfw", status: "unknown" },
  { id: 27, name: "terriblefacebookmemes", type: "sfw", status: "active" },
  { id: 28, name: "boottoobig", type: "sfw", status: "unknown" },
  { id: 29, name: "imsorryjon", type: "sfw", status: "unknown" },
  { id: 30, name: "SurrealMemes", type: "sfw", status: "unknown" },
  { id: 31, name: "DeepFriedMemes", type: "sfw", status: "unknown" },
  { id: 32, name: "Weird", type: "sfw", status: "unknown" },
  { id: 33, name: "CrappyDesign", type: "sfw", status: "unknown" },
  { id: 34, name: "madlads", type: "sfw", status: "active" },
  { id: 35, name: "rareinsults", type: "sfw", status: "unknown" },
  { id: 36, name: "firstworldanarchists", type: "sfw", status: "unknown" },
  { id: 37, name: "trippinthroughtime", type: "sfw", status: "unknown" },
  { id: 38, name: "pewdiepiesubmissions", type: "sfw", status: "unknown" },
  { id: 39, name: "ihadastroke", type: "sfw", status: "unknown" },
  { id: 40, name: "wholesomememes", type: "sfw", status: "actvie" },
  { id: 41, name: "collapse", type: "sfw", status: "actvie" },
  { id: 42, name: "ProgrammerHumor", type: "sfw", status: "active" },
  { id: 43, name: "humor", type: "sfw", status: "actvie" },
  { id: 44, name: "PoliticalHumor", type: "sfw", status: "actvie" },
  { id: 45, name: "funny", type: "sfw", status: "actvie" },
  { id: 46, name: "boomershumor", type: "sfw", status: "actvie" },
  { id: 47, name: "ComedyCemetry", type: "sfw", status: "actvie" },
  { id: 48, name: "programminghumor", type: "sfw", status: "actvie" },
  { id: 49, name: "bakchodi", type: "sfw", status: "actvie" },
  { id: 50, name: "formuladank", type: "sfw", status: "actvie" },
  { id: 51, name: "MinecraftMemes", type: "sfw", status: "actvie" },
  { id: 52, name: "stonks", type: "sfw", status: "actvie" },
  { id: 53, name: "AccountingMemes", type: "sfw", status: "actvie" },
  { id: 54, name: "RelationshipMemes", type: "sfw", status: "actvie" },
  { id: 55, name: "AnarchyChess", type: "sfw", status: "actvie" },
  { id: 56, name: "HockeyMemes", type: "sfw", status: "actvie" },
  { id: 57, name: "GymMemes", type: "sfw", status: "actvie" },
  { id: 58, name: "dndMemes", type: "sfw", status: "actvie" },
  { id: 59, name: "ROBOLOXmemes", type: "sfw", status: "actvie" },
  { id: 60, name: "shitposting", type: "sfw", status: "actvie" },
];

function getSubredditList() {
  return subredditArr;
}
